#  Original: https://www.tenforums.com/tutorials/158472-add-remove-command-prompt-open-here-context-menu-windows-10-a.html
#  Converted to powershell using Reg2CI

if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1\command" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2" -force -ea SilentlyContinue };
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2\command") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2\command" -force -ea SilentlyContinue };
Remove-Item -LiteralPath "HKLM:\SOFTWARE\Classes\LibraryFolder\Background\shell\CommandPrompt" -force;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt' -Name 'MUIVerb' -Value 'Command Prompt' -PropertyType String -Force -ea SilentlyContinue;
Remove-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt' -Name 'Extended' -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt' -Name 'SubCommands' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1' -Name '(default)' -Value '@shell32.dll,-8506' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1' -Name 'MUIVerb' -Value 'Open here' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1' -Name 'NoWorkingDirectory' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd1\command' -Name '(default)' -Value 'cmd.exe /s /k pushd %V\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2' -Name '(default)' -Value 'Open here as administrator' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2' -Name 'HasLUAShield' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2' -Name 'Icon' -Value 'imageres.dll,-5324' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\DesktopBackground\shell\CommandPrompt\shell\cmd2\command' -Name '(default)' -Value 'cmd /c echo|set/p=%V|powershell -NoP -W 1 -NonI -NoL SaPs ''cmd'' -Args ''/c cd /d'',$([char]34+$Input+[char]34),''^&^& start /b cmd.exe'' -Verb RunAs\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt' -Name 'MUIVerb' -Value 'Command Prompt' -PropertyType String -Force -ea SilentlyContinue;
Remove-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt' -Name 'Extended' -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt' -Name 'SubCommands' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1' -Name '(default)' -Value '@shell32.dll,-8506' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1' -Name 'MUIVerb' -Value 'Open here' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1' -Name 'NoWorkingDirectory' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd1\command' -Name '(default)' -Value 'cmd.exe /s /k pushd %V\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2' -Name '(default)' -Value 'Open here as administrator' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2' -Name 'HasLUAShield' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2' -Name 'Icon' -Value 'imageres.dll,-5324' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\shell\CommandPrompt\shell\cmd2\command' -Name '(default)' -Value 'cmd /c echo|set/p=%L|powershell -NoP -W 1 -NonI -NoL SaPs ''cmd'' -Args ''/c cd /d'',$([char]34+$Input+[char]34),''^&^& start /b cmd.exe'' -Verb RunAs\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt' -Name 'MUIVerb' -Value 'Command Prompt' -PropertyType String -Force -ea SilentlyContinue;
Remove-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt' -Name 'Extended' -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt' -Name 'SubCommands' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1' -Name '(default)' -Value '@shell32.dll,-8506' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1' -Name 'MUIVerb' -Value 'Open here' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1' -Name 'NoWorkingDirectory' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd1\command' -Name '(default)' -Value 'cmd.exe /s /k pushd %V\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2' -Name '(default)' -Value 'Open here as administrator' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2' -Name 'HasLUAShield' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2' -Name 'Icon' -Value 'imageres.dll,-5324' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Directory\Background\shell\CommandPrompt\shell\cmd2\command' -Name '(default)' -Value 'cmd /c echo|set/p=%V|powershell -NoP -W 1 -NonI -NoL SaPs ''cmd'' -Args ''/c cd /d'',$([char]34+$Input+[char]34),''^&^& start /b cmd.exe'' -Verb RunAs\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt' -Name 'MUIVerb' -Value 'Command Prompt' -PropertyType String -Force -ea SilentlyContinue;
Remove-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt' -Name 'Extended' -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt' -Name 'SubCommands' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1' -Name '(default)' -Value '@shell32.dll,-8506' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1' -Name 'MUIVerb' -Value 'Open here' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1' -Name 'Icon' -Value 'imageres.dll,-5323' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1' -Name 'NoWorkingDirectory' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd1\command' -Name '(default)' -Value 'cmd.exe /s /k pushd %V\' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2' -Name '(default)' -Value 'Open here as administrator' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2' -Name 'HasLUAShield' -Value '' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2' -Name 'Icon' -Value 'imageres.dll,-5324' -PropertyType String -Force -ea SilentlyContinue;
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\Drive\shell\CommandPrompt\shell\cmd2\command' -Name '(default)' -Value 'cmd /c echo|set/p=%L|powershell -NoP -W 1 -NonI -NoL SaPs ''cmd'' -Args ''/c cd /d'',$([char]34+$Input+[char]34),''^&^& start /b cmd.exe'' -Verb RunAs\' -PropertyType String -Force -ea SilentlyContinue;